# Generated by Django 3.1.1 on 2020-10-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201029_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
