# Generated by Django 3.1.1 on 2020-11-05 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_ids', models.CharField(default=0, max_length=60)),
                ('product_ids', models.CharField(default=0, max_length=60)),
                ('invoice_id', models.CharField(default=0, max_length=60)),
                ('first_name', models.CharField(max_length=90)),
                ('last_name', models.CharField(max_length=90)),
                ('state', models.CharField(max_length=111)),
                ('address', models.CharField(max_length=111)),
                ('address2', models.CharField(blank=True, max_length=111, null=True)),
                ('city', models.CharField(max_length=111)),
                ('zip_code', models.CharField(max_length=111)),
                ('phone', models.CharField(default='', max_length=111)),
                ('email', models.CharField(max_length=111)),
                ('amount', models.PositiveIntegerField()),
                ('payment_status', models.BooleanField(default=False)),
                ('processed_on', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ManyToManyField(default=1, to='cart.UserCart')),
                ('owner_id', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
