# Generated by Django 3.1.1 on 2020-10-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=90)),
                ('last_name', models.CharField(max_length=90)),
                ('state', models.CharField(max_length=111)),
                ('address', models.CharField(max_length=111)),
                ('address2', models.CharField(blank=True, max_length=111, null=True)),
                ('city', models.CharField(max_length=111)),
                ('zip_code', models.CharField(max_length=111)),
                ('phone', models.CharField(default='', max_length=111)),
                ('email', models.CharField(max_length=111)),
                ('amount', models.PositiveIntegerField()),
                ('cart', models.ManyToManyField(default=1, to='cart.UserCart')),
            ],
        ),
    ]
