# Generated by Django 3.1.1 on 2020-10-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20201006_1224'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(default=1, to='cart.UserCart'),
        ),
    ]
