# Generated by Django 3.1.1 on 2020-11-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_userorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
