# Generated by Django 3.1.1 on 2020-10-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201004_2321'),
        ('cart', '0004_auto_20201005_2241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart_item',
            new_name='CartItem',
        ),
    ]
